export default {
  title: 'About',
  name: 'about',
  __experimental_actions: [/*'create',*/ 'update', /*'delete',*/ 'publish'],
  type: 'document',
  fields: [
    {
      title: 'Title',
      name: 'title',
      type: 'string',
    },
    {
      title: 'Home summary',
      name: 'homeSummary',
      type: 'array',
      of: [{ type: 'block' }],
      description: 'Short summary for the homepage.',
      validation: (Rule) => Rule.required().error('Required field'),
    },
    {
      title: 'Excerpt',
      name: 'excerpt',
      type: 'array',
      of: [{ type: 'block' }],
      description: 'Top section in about page.',
      validation: (Rule) => Rule.required().error('Required field'),
    },
    {
      title: 'Personal',
      name: 'personalBody',
      type: 'array',
      of: [{ type: 'block' }, { type: 'image' }],
      description: 'Content for personal section.',
      validation: (Rule) => Rule.required().error('Required field'),
    },
    {
      title: 'Work Experience',
      name: 'workExperience',
      type: 'array',
      of: [{ type: 'workExperience' }],
      description: 'Add work history here',
    },
    {
      title: 'Skills',
      name: 'skills',
      type: 'array',
      of: [{ type: 'skill' }],
      description: 'Add list of skills here.',
    },
    {
      title: 'Description',
      name: 'description',
      type: 'text',
      description: 'Short description for SEO',
    },
  ],
};
